language: python
sudo: required
dist: trusty

python:
  - "3.4"

virtualenv:
  system_site_packages: true

env:
 - QT_API=pyqt4
 - QT_API=pyqt5

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
 - sudo apt-get update

 # Qt
 - python scripts/install-qt.py

 # OpenCOBOL
 - sudo apt-get install -y -qq open-cobol --fix-missing

 # pytest
 - pip install --quiet pytest pytest-cov

 # coveralls
 - pip install --quiet coveralls --use-wheel

script:
 - pip install -e .
 - catchsegv py.test --cov pyqode

after_success:
 - coveralls
